version: "3.9"

networks:
  deploy-guide-dev:
    driver: bridge

services:
  app:
    container_name: iShopMain
    image: ${DOCKER_REGISTRY}ishopmain
    build:
      context: .
      dockerfile: ishopmain/Dockerfile
    ports:
     - "80:80"
     - "443:443"
    networks:
     - deploy-guide-dev
    depends_on:
     - iShopDataBase
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=passwordmaster
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/dev_cert.pfx
    volumes:
      - ./iShopMain/conf.d/https/:/https/

  iShopDataBase:
    image: postgres:15.2
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: iShopDataBase
    ports:
     - "5432:5432"
    networks:
     - deploy-guide-dev
    volumes:
     - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: 

